config/routes.rb
class OwnerNameContraint
  BLACKLIST = [
    "javascripts",
    "stylesheets",
    "assets",
  ].freeze

  def self.matches?(request)
    !new(request).blacklisted?
  end

  def initialize(request)
    @request = request
  end

  def blacklisted?
    BLACKLIST.include?(owner_name)
  end

  private

  def owner_name
    @request.params[:owner_name]
  end
end

REPOSITORY_NAME_REGEXP = %r{[^/]+}

TravisLite::Application.routes.draw do
  get "jobs/show"
  resources :repositories, path: ':owner_name', only: :index, param: :name, constraints: OwnerNameContraint do
    member do
      get :show, name: REPOSITORY_NAME_REGEXP
    end
    resources :builds, only: %i[index show], repository_name: REPOSITORY_NAME_REGEXP
    resources :jobs, only: %i[show], repository_name: REPOSITORY_NAME_REGEXP
  end

  root "repositories#index"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/builds_controller.rb
class BuildsController < ApplicationController
  def index
  end

  def show
    @build = BuildDecorator.decorate(Travis::Build.find(params[:id]))
    if @build.jobs.length == 1
      redirect_to repository_job_url(@build.jobs.first.url_info)
    end
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  def show
    @job = JobDecorator.decorate(Travis::Job.find(params[:id]))
  end
end

app/controllers/repositories_controller.rb
class RepositoriesController < ApplicationController
  def index
    if params[:owner_name]
      collection = Travis::Repository.find_all(params.slice(:owner_name))
    else
      collection = Travis::Repository.current
    end
    @repositories = RepositoryDecorator.decorate_collection(collection)
  end

  def show
    @repository = RepositoryDecorator.decorate(Travis::Repository.find(slug))
  end

  private

  def slug
    "#{params[:owner_name]}/#{params[:name]}"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/builds_helper.rb
module BuildsHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/repositories_helper.rb
module RepositoriesHelper
end

app/views/builds/show.html.slim
== render partial: "shared/repository_header", locals: { repository: @build.repository, header_info: "Build #{@build.number}" }

h2 Build Matrix

table.table
  thead
    tr
      th Job
      th Job status
      th Duration
      th Finished
  tbody
    - @build.jobs.each do |job|
      tr class=job.row_class
        td = link_to(job.number, repository_job_path(job.url_info))
        td = job.state
        td = job.duration
        td = job.finished_at

app/views/jobs/show.html.slim
== render partial: "shared/repository_header", locals: { repository: @job.repository, header_info: "Job #{@job.number}" }

ul
  li
    ' Repo:
    = link_to(@job.repository.slug, repository_path(@job.repository.url_info))
  li
    ' Build
    = link_to(@job.build.number, repository_build_path(@job.build.url_info))
  li
    ' Status:
    span.label class="label-#{@job.row_class}"
      = @job.state
  li
    ' Branch:
    = @job.commit.branch
  li
    ' Language:
    = @job.language
  li
    ' Compare on
    = link_to("GitHub", @job.commit.compare_url)
  li
    | Message:
    pre = @job.commit.message

h2 Config

pre = @job.config

h2 Log

- if @job.log
  = link_to("Go to bottom of log", "#log-bottom")
  pre = @job.log.clean_body
  div#log-bottom
- else
  p Log could not be found.

app/views/layouts/application.html.slim
doctype html
html
  head
    title Travis Lite

    meta name="viewport" content="width=device-width, initial-scale=1.0"

    = stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags

    javascript:
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-41126684-1', 'travis-lite.com');
      ga('send', 'pageview');

  body
    .navbar.navbar-inverse
      .navbar-inner
        a.brand href=root_path Travis Lite

        ul.nav.pull-right
          li
            a href="https://github.com/henrikhodne/travis-lite"
              | Travis Lite on GitHub

    .container
      == yield

app/views/repositories/index.html.slim
h2
  - if params[:owner_name]
    | #{params[:owner_name]}'s repositories
  - else
    | Latest Builds

table.table
  thead
    tr
      th Repository Name
      th Last Build
      th Last Build Status
  tbody
  - @repositories.each do |repository|
    tr class=repository.row_class
      td
        =' link_to(repository.owner_name, repositories_path(owner_name: repository.owner_name))
        ' /
        =  link_to(repository.name, repository_path(repository.url_info))
      td = link_to(repository.last_build_number, repository_build_path(repository.last_build_url_info))
      td = repository.last_build_state

app/views/repositories/show.html.slim
== render partial: "shared/repository_header", locals: { repository: @repository }

table.table
  thead
    tr
      th Build
      th Build status
      th Commit
      th Message

  tbody
    - @repository.builds.each do |build|
      tr class=build.row_class
        td = link_to(build.number, repository_build_path(build.url_info))
        td = build.state
        td = build.commit_info
        td = build.commit.subject

app/views/shared/_repository_header.html.slim
header
  h1
    =' link_to(repository.owner_name, repositories_path(owner_name: repository.owner_name))
    ' /
    =' link_to(repository.name, repository_path(repository.url_info))

    - if defined?(header_info)
      ' –
      =' header_info